Web/AllAboutBoxing.Web/Areas/Administration/Controllers/AdministrationController.cs
namespace AllAboutBoxing.Web.Areas.Administration.Controllers
{
    using AllAboutBoxing.Common;
    using AllAboutBoxing.Web.Controllers;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
    [Area("Administration")]
    public class AdministrationController : BaseController
    {
    }
}

Web/AllAboutBoxing.Web/Controllers/BaseController.cs
namespace AllAboutBoxing.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class BaseController : Controller
    {
    }
}

Web/AllAboutBoxing.Web/Controllers/BoxersController.cs
namespace AllAboutBoxing.Web.Controllers
{
    using AllAboutBoxing.Services.Data;
    using AllAboutBoxing.Web.ViewModels.Boxers;
    using Microsoft.AspNetCore.Mvc;

    public class BoxersController : Controller
    {
        private readonly IBoxersService boxersService;

        public BoxersController(IBoxersService boxersService)
        {
            this.boxersService = boxersService;
        }

        public IActionResult All(int id = 1)
        {
            const int itemsPerPage = 12;
            var viewModel = new BoxersListViewModel
            {
                ItemsPerPage = itemsPerPage,
                PageNumber = id,
                BoxersCount = this.boxersService.GetCount(),
                Boxers = this.boxersService.GetAll(id, itemsPerPage),
            };

            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var boxer = this.boxersService.GetById<SingleBoxerViewModel>(id);
            return this.View(boxer);
        }

        public IActionResult SearchByName(string name)
        {
            var boxerViewModel = this.boxersService.GetByName<BoxerInListViewModel>(name);

            if (boxerViewModel == null)
            {
                return this.Redirect("All");
            }

            return this.View(boxerViewModel);
        }
    }
}

Web/AllAboutBoxing.Web/Controllers/ChampionsController.cs
namespace AllAboutBoxing.Web.Controllers
{
    using AllAboutBoxing.Services.Data;
    using AllAboutBoxing.Web.ViewModels.Champions;
    using Microsoft.AspNetCore.Mvc;

    public class ChampionsController : Controller
    {
        private readonly IChampionsService championsService;

        public ChampionsController(IChampionsService championsService)
        {
            this.championsService = championsService;
        }

        public IActionResult Index()
        {
            var viewModel = new ChampionsListViewModel
            {
                ChampionsCount = this.championsService.GetCount(),
                Champions = this.championsService.GetAll(),
            };

            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            return this.Redirect($"/Boxers/ById/{id}");
        }
    }
}

Web/AllAboutBoxing.Web/Controllers/HallOfFameController.cs
namespace AllAboutBoxing.Web.Controllers
{
    using AllAboutBoxing.Services.Data;
    using AllAboutBoxing.Web.ViewModels.HallOfFame;
    using Microsoft.AspNetCore.Mvc;

    public class HallOfFameController : Controller
    {
        private readonly IHallOfFameService hallOfFameService;

        public HallOfFameController(IHallOfFameService hallOfFameService)
        {
            this.hallOfFameService = hallOfFameService;
        }

        public IActionResult Index(int id = 1)
        {
            const int itemsPerPage = 1;

            var viewModel = new HallOfFameBoxersListViewModel
            {
                ItemsPerPage = itemsPerPage,
                PageNumber = id,
                BoxersCount = this.hallOfFameService.GetCount(),
                HallOfFameBoxers = this.hallOfFameService.GetAll(id, itemsPerPage),
            };

            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            return this.Redirect($"/Boxers/ById/{id}");
        }
    }
}

Web/AllAboutBoxing.Web/Controllers/HomeController.cs
namespace AllAboutBoxing.Web.Controllers
{
    using System.Diagnostics;

    using AllAboutBoxing.Services.Data;
    using AllAboutBoxing.Web.ViewModels;
    using Microsoft.AspNetCore.Mvc;

    public class HomeController : BaseController
    {
        private readonly IGetCountsService getCountsService;

        public HomeController(IGetCountsService getCountsService)
        {
            this.getCountsService = getCountsService;
        }

        public IActionResult Index()
        {
            var viewModel = this.getCountsService.GetCounts();
            return this.View(viewModel);
        }

        public IActionResult Privacy()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

Web/AllAboutBoxing.Web/Controllers/NewsController.cs
namespace AllAboutBoxing.Web.Controllers
{
    using AllAboutBoxing.Services.Data;
    using AllAboutBoxing.Web.ViewModels.News;
    using Microsoft.AspNetCore.Mvc;

    public class NewsController : Controller
    {
        private readonly INewsService newsService;

        public NewsController(INewsService newsService)
        {
            this.newsService = newsService;
        }

        public IActionResult Index(int id = 1)
        {
            const int itemsPerPage = 5;

            var viewModel = new NewsListViewModel
            {
                ItemsPerPage = itemsPerPage,
                PageNumber = id,
                NewsCount = this.newsService.GetCount(),
                NewsList = this.newsService.GetAllNews<NewsViewModel>(id, itemsPerPage),
            };

            return this.View(viewModel);
        }

        public IActionResult NewsById(int id)
        {
            var newById = this.newsService.GetById<NewsViewModel>(id);
            return this.View(newById);
        }
    }
}

Web/AllAboutBoxing.Web/Controllers/RankingsController.cs
namespace AllAboutBoxing.Web.Controllers
{
    using AllAboutBoxing.Services.Data.Rankings;
    using AllAboutBoxing.Web.ViewModels.Rankings;
    using Microsoft.AspNetCore.Mvc;

    public class RankingsController : Controller
    {
        private readonly IRankingsService rankingsService;

        public RankingsController(IRankingsService rankingsService)
        {
            this.rankingsService = rankingsService;
        }

        public IActionResult Index()
        {
            var viewModel = new RankigsListViewModel
            {
                Rankings = this.rankingsService.GetAll(),
            };

            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            return this.Redirect($"/Boxers/ById/{id}");
        }
    }
}

Web/AllAboutBoxing.Web/Controllers/WeightClassesController.cs
namespace AllAboutBoxing.Web.Controllers
{
    using AllAboutBoxing.Services.Data;
    using AllAboutBoxing.Web.ViewModels.WeightClasses;
    using Microsoft.AspNetCore.Mvc;

    public class WeightClassesController : Controller
    {
        private readonly IWeightClassesService weightClassesService;

        public WeightClassesController(IWeightClassesService weightClassesService)
        {
            this.weightClassesService = weightClassesService;
        }

        public IActionResult Index()
        {
            var viewModel = new WeightClassesListViewModel
            {
                WeightClasses = this.weightClassesService.GetAll(),
            };

            return this.View(viewModel);
        }

        public IActionResult WeightClassById(int id)
        {
            var weightClass = this.weightClassesService.GetById<SingleWeightClassViewModel>(id);
            return this.View(weightClass);
        }
    }
}

Web/AllAboutBoxing.Web/Views/Boxers/All.cshtml
@model AllAboutBoxing.Web.ViewModels.Boxers.BoxersListViewModel
@{
    this.ViewData["Title"] = "Featured boxers";
}

<h1 class="text-center">@this.ViewData["Title"]</h1>
<hr />

<form class="text-center font-weight-bold" asp-action="SearchByName" method="get">
    <div class="form-actions no-color col justify-content-center">
        <span class="ml-5">Find by name</span>
        <span>
            <input type="text" name="name" value="@ViewData["CurrentFilter"]"/>
        </span>
        <span>
            <input type="submit" value="Search" class="btn" />
        </span>
    </div>
</form>

<hr />

<div class="row list-group-item-dark">
    @foreach (var boxer in this.Model.Boxers)
    {
        <div class="media col-md-3 card-columns card-body">
            <img src="@boxer.ImageUrl" width="100" height="125" class="mr-3 img-responsive">
            <div class="media-body">
                <h5><a class="font-weight-bold" asp-action="ById" asp-route-id="@boxer.Id">@boxer.Name</a></h5>
                <span><img src="@boxer.CountryFlagUrl"></span>
            </div>
        </div>
    }
</div>

<hr />

<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage)  { <text>disabled</text> }">
            <a class="page-link btn-outline-danger" asp-action="All" asp-route-id="@Model.PreviousPageNumber">Previous</a>
        </li>
        @for (int i = Model.PageNumber - 3; i < Model.PageNumber; i++)
        {
            @if (i > 0)
            {
                <li class="page-item "><a class="page-link btn-outline-danger" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }

        <li class="page-item active">
            <span class="page-link bg-danger">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>

        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 3; i++)
        {
            @if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link btn-outline-danger" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage)  { <text>disabled</text> }">
            <a class="page-link btn-outline-danger" asp-action="All" asp-route-id="@Model.NextPageNumber">Next</a>
        </li>
    </ul>
</nav>

Web/AllAboutBoxing.Web/Views/Boxers/ById.cshtml
@model AllAboutBoxing.Web.ViewModels.Boxers.SingleBoxerViewModel

@{
    this.ViewData["Title"] = @Model.Name;
}

<h1>@this.ViewData["Titlе"]</h1>
<hr />

<div>
    <img src="@Model.ImageUrl" class="float-right" style="width:215px;height:300px;">
    <div class="text-center font-weight-bold">
        <h2 class="row col-md-8 d-inline-block">@Model.Name (@Model.Record.Wins-@Model.Record.Loses-@Model.Record.Draws) <img src="@Model.Country.FlagUrl" /></h2>

        <ul class="d-block">
            <li class="row col-md-8 table-dark font-weight-bold text-uppercase text-center">Boxers profile</li>
            <li class="row">
                <span class="col-md-2 bg-danger">Status</span>
                @if (Model.IsActive)
                {
                    <span class="col-md-8 bg-success">Active</span>
                }
                else
                {
                    <span class="col-md-8 bg-success">Inactive</span>
                }
            </li>
            <li class="row"><span class="col-md-2 bg-danger">Alias</span><span class="col-md-8 bg-success">@Model.Alias</span></li>
            @if (Model.IsActive)
            {
                <li class="row"><span class="col-md-2 bg-danger">Age</span><span class="col-md-8 bg-success">@Model.Age</span></li>
            }
            <li class="row"><span class="col-md-2 bg-danger">BirthDate</span><span class="col-md-8 bg-success">@Model.BirthDate</span></li>
            @if (Model.DeathDate != null)
            {
                <li class="row"><span class="col-md-2 bg-danger">DeathDate</span><span class="col-md-8 bg-success">@Model.DeathDate</span></li>
            }
            <li class="row"><span class="col-md-2 bg-danger">Height </span><span class="col-md-8 bg-success">@Model.Height</span></li>
            <li class="row"><span class="col-md-2 bg-danger">Reach </span><span class="col-md-8 bg-success"> @Model.Reach</span></li>
            <li class="row"><span class="col-md-2 bg-danger">Country</span><span class="col-md-8 bg-success">@Model.Country.Name</span></li>
            @if (!Model.IsActive)
            {
                <li class="row"><span class="col-md-2 bg-danger">Residence</span><span class="col-md-8 bg-success">@Model.Residence</span></li>
            }
            else
            {
                <li class="row"><span class="col-md-2 bg-danger">Residence</span><span class="col-md-8 bg-success">@Model.Residence</span></li>
            }
        </ul>
        <hr />
        <ul>
            <li class="row col-md-8 table-dark font-weight-bold text-uppercase">Full record</li>
            <li class="row"><span class="col-md-2 bg-danger">Division</span><span class="col-md-6 bg-success">@Model.WeightClass.Division</span></li>
            <li class="row"><span class="col-md-2 bg-danger">Wins </span><span class="col-md-6 bg-success">@Model.Record.Wins</span></li>
            <li class="row"><span class="col-md-2 bg-danger">By KO </span><span class="col-md-6 bg-success">@Model.Record.Kos</span></li>
            <li class="row"><span class="col-md-2 bg-danger">KO% </span><span class="col-md-6 bg-success">@Math.Ceiling((Model.Record.Kos) * 1.0 / (Model.Record.Wins) * 100)%</span></li>
            <li class="row"><span class="col-md-2 bg-danger">Lost </span><span class="col-md-6 bg-success">@Model.Record.Loses</span></li>
            <li class="row"><span class="col-md-2 bg-danger">Draws </span><span class="col-md-6 bg-success">@Model.Record.Draws</span></li>
            <li class="row"><span class="col-md-2 bg-danger">Debut </span><span class="col-md-6 bg-success">@Model.Debut</span></li>
        </ul>
    </div>
</div>
<hr />

<div>
    <p>@Model.Description</p>
</div>

<hr />

@if (Model.Bouts.Any())
{

    <h2 class="text-center">Professional boxing record</h2>

    <table class="table table-striped table-hover text-center table-responsive-sm">
        <thead class="thead-dark">
            <tr>
                <th>Date</th>
                <th>Opponent</th>
                <th>Place</th>
                <th>Titles</th>
                <th>Result</th>
            </tr>
        </thead>
        <tbody>
             
            @foreach (var bout in Model.Bouts.OrderByDescending(x => x.DateOfBout))
            {
                <tr>
                    <td class="d-inline-block text-truncate">
                        @bout.BoutDate
                    </td>
                    <td>
                        @bout.OpponentName
                    </td>
                    <td>
                        @bout.Place
                    </td>
                    <td>
                        @bout.TitlesInFight
                    </td>
                    <td>
                        @if (bout.WayOfFinish.StartsWith("WIN"))
                        {
                            <span class="text-success font-weight-bold">@bout.WayOfFinish</span>
                        }
                        else if (bout.WayOfFinish.StartsWith("LOSS"))
                        {
                            <span class="text-danger font-weight-bold">@bout.WayOfFinish</span>
                        }
                        else
                        {
                            <span class="text-secondary font-weight-bold">@bout.WayOfFinish</span>
                        }
                    </td>
                </tr>
            }
    </table>
}

Web/AllAboutBoxing.Web/Views/Boxers/SearchByName.cshtml
@model AllAboutBoxing.Web.ViewModels.Boxers.BoxerInListViewModel
@{
    this.ViewData["Title"] = Model.Name;
}

<h1 class="text-center">@this.ViewData["Title"]</h1>

<hr />

<div class="text-center">
    <img src="@Model.ImageUrl">
    <h5><a class="font-weight-bold" asp-action="ById" asp-route-id="@Model.Id">@Model.Name</a></h5>
    <img src="@Model.CountryFlagUrl">
    <p><a class="font-weight-bold" asp-action="All">Back to full list</a></p>
</div>

Web/AllAboutBoxing.Web/Views/Champions/Champions.cshtml
@model AllAboutBoxing.Web.ViewModels.Champions.ChampionsListViewModel
@{
    this.ViewData["Title"] = "Champions";
}

@section Styles{ 
<link rel="stylesheet" href="~/css/HighChart/Index.css"/>
}

<h1 class="text-center">@this.ViewData["Title"]</h1>

<hr />

@foreach (var champion in Model.Champions)
{
    <div class="text-center list-group-item-info">
        <h3>
            <a class="font-weight-bold" asp-action="ById" asp-route-id="@champion.Id">@champion.ChampionName  </a><span><img src="@champion.CountryFlagUrl"></span>
        </h3>
        <h3 class="col-md-12 text-center">@champion.Organization - @champion.WeightLimit</h3>
        <img src="@champion.ImageUrl" class="rounded mx-auto d-block">
    </div>
    <hr />
}

<div class="buttons">
    <button id="2000">
        2000
    </button>
    <button id="2004">
        2004
    </button>
    <button id="2008">
        2008
    </button>
    <button id="2012">
        2012
    </button>
    <button id="2016" class="active">
        2016
    </button>
</div>
<div id="container"></div>

@section Scripts{
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="~/js/HighCharts/Index.js"></script>
}

Web/AllAboutBoxing.Web/Views/Champions/Index.cshtml
@model AllAboutBoxing.Web.ViewModels.Champions.ChampionsListViewModel
@{
    this.ViewData["Title"] = "Champions";
}

@section Styles{ 
<link rel="stylesheet" href="~/css/HighChart/Index.css"/>
}

<h1 class="text-center">@this.ViewData["Title"]</h1>

<hr />

@foreach (var champion in Model.Champions)
{
    <div class="text-center list-group-item-info">
        <h3>
            <a class="font-weight-bold" asp-action="ById" asp-route-id="@champion.Id">@champion.ChampionName  </a><span><img src="@champion.CountryFlagUrl"></span>
        </h3>
        <h3 class="col-md-12 text-center">@champion.Organization - @champion.WeightLimit</h3>
        <img src="@champion.ImageUrl" class="rounded mx-auto d-block">
    </div>
    <hr />
}

<div class="buttons">
    <button id="2000">
        2000
    </button>
    <button id="2004">
        2004
    </button>
    <button id="2008">
        2008
    </button>
    <button id="2012">
        2012
    </button>
    <button id="2016" class="active">
        2016
    </button>
</div>
<div id="container"></div>

@section Scripts{
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="~/js/HighCharts/Index.js"></script>
}

Web/AllAboutBoxing.Web/Views/HallOfFame/HallOfFame.cshtml
@model AllAboutBoxing.Web.ViewModels.HallOfFame.HallOfFameBoxersListViewModel
@{
    this.ViewData["Title"] = "The greatest boxers of all time";
}

<h1 class="text-center">@this.ViewData["Title"]</h1>

<hr />
<p class="text-center">Mike Tyson, Joe Frazier and of course Muhammad Ali — there have been many legendary boxers. Here's our list of the very best.</p>
<hr />

@foreach (var boxer in Model.HallOfFameBoxers)
{
    <div class="text-center list-group-item-dark">
        <div class="teaserImg">
            <img class="table-responsive-sm" src="@boxer.BoxerImageUrl">
        </div>
        <div class="teaserContentWrap">
            <div class="tools">
            </div>
            <h3>
                <a class="font-weight-bold" asp-action="ById" asp-route-id="@boxer.Id">@boxer.BoxerName</a>
            </h3>
            <p>@boxer.Description</p>
        </div>
    </div>
}

<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage)  { <text>disabled</text> }">
            <a class="page-link btn-outline-danger" asp-action="HallOfFame" asp-route-id="@Model.PreviousPageNumber">Previous</a>
        </li>
        @for (int i = Model.PageNumber - 2; i < Model.PageNumber; i++)
        {
            @if (i > 0)
            {
                <li class="page-item"><a class="page-link btn-outline-danger" asp-action="HallOfFame" asp-route-id="@i">@i</a></li>
            }
        }

        <li class="page-item active">
            <span class="page-link bg-danger">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>

        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 2; i++)
        {
            @if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link btn-outline-danger" asp-action="HallOfFame" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage)  { <text>disabled</text> }">
            <a class="page-link btn-outline-danger" asp-action="HallOfFame" asp-route-id="@Model.NextPageNumber">Next</a>
        </li>
    </ul>
</nav>

Web/AllAboutBoxing.Web/Views/HallOfFame/Index.cshtml
@model AllAboutBoxing.Web.ViewModels.HallOfFame.HallOfFameBoxersListViewModel
@{
    this.ViewData["Title"] = "The greatest boxers of all time";
}

<h1 class="text-center">@this.ViewData["Title"]</h1>

<hr />
<p class="text-center">Mike Tyson, Joe Frazier and of course Muhammad Ali — there have been many legendary boxers. Here's our list of the very best.</p>
<hr />

@foreach (var boxer in Model.HallOfFameBoxers)
{
    <div class="text-center list-group-item-dark">
        <div class="teaserImg">
            <img class="table-responsive-sm" src="@boxer.BoxerImageUrl">
        </div>
        <div class="teaserContentWrap">
            <div class="tools">
            </div>
            <h3>
                <a class="font-weight-bold" asp-action="ById" asp-route-id="@boxer.Id">@boxer.BoxerName</a>
            </h3>
            <p>@boxer.Description</p>
        </div>
    </div>
}

<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage)  { <text>disabled</text> }">
            <a class="page-link btn-outline-danger" asp-action="Index" asp-route-id="@Model.PreviousPageNumber">Previous</a>
        </li>
        @for (int i = Model.PageNumber - 2; i < Model.PageNumber; i++)
        {
            @if (i > 0)
            {
                <li class="page-item"><a class="page-link btn-outline-danger" asp-action="Index" asp-route-id="@i">@i</a></li>
            }
        }

        <li class="page-item active">
            <span class="page-link bg-danger">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>

        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 2; i++)
        {
            @if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link btn-outline-danger" asp-action="Index" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage)  { <text>disabled</text> }">
            <a class="page-link btn-outline-danger" asp-action="Index" asp-route-id="@Model.NextPageNumber">Next</a>
        </li>
    </ul>
</nav>

Web/AllAboutBoxing.Web/Views/Shared/_Layout.cshtml
@using AllAboutBoxing.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/lazy.css"/>
    @await this.RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-danger border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i> Home</a>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="btn btn-group dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Rankings
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Rankings" asp-action="Index">Rankings</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="WeightClasses" asp-action="Index">WeightClasses</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Champions" asp-action="Index"><i class="fas fa-crown"></i> Champions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Boxers" asp-action="All"><i class="fas fa-hand-rock"></i> Boxers</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="HallOfFame" asp-action="Index"><i class="fas fa-archive"></i> HallOfFame</a>
                            </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="News" asp-action="Index"><i class="fas fa-globe-europe"></i> News</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <nav class="alert-dark">
            <div class="table-responsive-sm text-center">
                &copy; @DateTime.Now.Year - ©AllAboutBoxing : data may be incomplete/inaccurate.  @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy & Cookie Policy</a>
            </div>            
        </nav>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/js/lazy.js" asp-append-version="true"></script>

    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>